package fr.cristal.emeraude.n2s3.models.qbg

import akka.actor._
import fr.cristal.emeraude.n2s3.core.Spike

/**
 * Simulate a pre-synaptic spike, normally generated by neurons
 */
case class PreSynapticSpike(override val timestamp: Int, override val destination: ActorRef) extends Spike(timestamp, destination)

/**
 * Simulate a post-synaptic forward spike, generated by  synapses
 */
case class PostSynapticForwardSpike(override val timestamp: Int, override val destination: ActorRef) extends Spike(timestamp, destination)

/**
 * Simulate a post-synaptic backward spike, generated by neurons
 */
case class PostSynapticBackwardSpike(override val timestamp: Int, override val destination: ActorRef, sender: ActorRef) extends Spike(timestamp, destination)
